#if !canImport(ObjectiveC)
import XCTest

extension WebShellCoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WebShellCoreTests = [
        ("testAsciiMD5", testAsciiMD5),
        ("testExample", testExample),
        ("testPublisherToAsyncValue", testPublisherToAsyncValue),
        ("testZonesPublisherToAsyncValue", testZonesPublisherToAsyncValue),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(WebShellCoreTests.__allTests__WebShellCoreTests),
    ]
}
#endif
